//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace pracMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class blueMap_Job
    {
        public int intID { get; set; }
        public string schoolNo { get; set; }
        public string CodeNo { get; set; }
        public string grade { get; set; }
        public string Name1 { get; set; }
        public Nullable<int> dataCount1 { get; set; }
        public Nullable<decimal> Ratio1 { get; set; }
        public string Name2 { get; set; }
        public Nullable<int> dataCount2 { get; set; }
        public Nullable<decimal> Ratio2 { get; set; }
        public string Name3 { get; set; }
        public Nullable<int> dataCount3 { get; set; }
        public Nullable<decimal> Ratio3 { get; set; }
        public string Name4 { get; set; }
        public Nullable<int> dataCount4 { get; set; }
        public Nullable<decimal> Ratio4 { get; set; }
        public byte type { get; set; }
        public byte sort { get; set; }
    }
}
